#handlers = java.util.logging.ConsoleHandler
handlers = org.slf4j.bridge.SLF4JBridgeHandler

# Set the default logging level for the root logger
.level = ALL

# Set the default formatter for new ConsoleHandler instances
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
